### ISSUE TITLE
[Solved] org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop table if exists user cascade " via JDBC [Syntax error in SQL statement "drop table if exists [*]user cascade "; expected "identifier";]

### ISSUE THREAD

**Issue by slykid** [slykid/Java#1]
* 현상: SpringBoot Application 실행 시, 위의 "org.hibernate.tool.schema.spi.CommandAcceptanceException" 예외가 발생함

* 원인: 
  * drop table if exists [*] user cascade에서 식별자가 필요하다는 에러를 뱉어냄
  * User라는 테이블을 삭제하라는 쿼리문에서, user가 예약어이기 때문에 조치가 필요함

* 처리
  * 방안은 크게 3가지가 존재함
    * @Table 애너테이션을 붙여 매핑 테이블 이름을 변경
    * 설정 파일에서 설정을 통해 예약어가 아님을 명시
   ```
   [application.yaml]
   spring:
     datasource:
       url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
   ```
   * User 클래스명 → Member 클래스 및 변수명 리펙터링

* 해결방안: 3번째 방안이 무난하여 리펙터링 수행 완료
